[package]
name = "es-copy-indices"
version = "1.14.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.16.0", default-features = false, features = ["config", "derive"] }
walkdir = "2.5.0"
zip = "8.6.0"
axum = { version = "0.8.9", features = ["macros"] }
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.6", features = ["cargo", "derive", "env"] }
human_bytes = { version = "0.4.3", features = ["fast"] }
logging_timer = "1.1.1"
memory-stats = "1.2.0"
reqwest = { version = "0.13.4", features = ["query", "json"] }
rustls = "0.23.43"
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = "3.22.0"
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["full"] }
tokio-retry = "0.3.2"
tokio-stream = { version = "0.1.19", features = ["sync"] }
toml = "1.1.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json", "fmt"] }
twelf = { version = "0.15.0", features = ["toml", "json"] }
libc = "0.2.189"
zstd = "0.13.3"
